name: ateam

on:
  pull_request:
    branches:
      - main
    types: [opened, edited]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Trigger pipeline
        run: echo Hello world!
