name: Python Package

on:
  pull_request:
    branches:
      - main
    types: [opened, edited]

jobs:
  pipeline:

    runs-on: ubuntu-latest

    steps:
      - name: Trigger pipeline
        run: echo Hello world!
